server:
  port: 8080

wx:
  miniapp:
    appid: ${WX_APPID:wx88888888}
    secret: ${WX_SECRET:secret88888}
    token: ${WX_TOKEN:token88888}
    aesKey: ${WX_AES_KEY:aesKey88888888}
    msgDataFormat: JSON

spring:
  application:
    name: fitness-user
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/fitness_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.fitness.**.model.entity
  configuration:
    map-underscore-to-camel-case: true
